name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    tags: ["*"]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Apt packages
        run: sudo apt-get update

      - name: Setup | Rust toolchain
        uses: dtolnay/rust-toolchain@1.79.0
        with:
          components: clippy, rustfmt

      - name: Setup | Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Hygiene | Formatting
        run: cargo fmt -- --check

      - name: Hygiene | Clippy
        run: cargo clippy -- -Dclippy::all -Dwarnings

      - name: Run | Test
        run: |
          cargo test --test serial
          cargo test --test parallel --features parallel
